project_id = "ymexlslqsdflgkcvwjoz"

[functions.pagarme-webhook]
verify_jwt = false

[functions.resolve-maps-url]
verify_jwt = false

[functions.invite-preview]
verify_jwt = false

[functions.invite-signup]
verify_jwt = false

[functions.external-auth]
verify_jwt = false
