// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/get_my_profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Return the signed-in user's Mayla profile (name, company, birth date, biological sex).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("user_id, full_name, birth_date, biological_sex, company_id, avatar_url, points").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/list_my_appointments.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.99.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_appointments_default = defineTool2({
  name: "list_my_appointments",
  title: "List my appointments",
  description: "List the signed-in user's upcoming and recent medical appointments.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(10).describe("Max number of appointments to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const { data, error } = await supabase.from("appointments").select("id, scheduled_at, status, mode, specialty, doctor_name, notes").eq("user_id", ctx.getUserId()).order("scheduled_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { appointments: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get_my_health_summary.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.99.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_health_summary_default = defineTool3({
  name: "get_my_health_summary",
  title: "Get my health summary",
  description: "Return the signed-in user's latest health scores and most recent vital signs measurement. Descriptive only \u2014 never diagnostic.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    const userId = ctx.getUserId();
    const [scores, vitals] = await Promise.all([
      supabase.from("health_scores").select("physical_score, emotional_score, lifestyle_score, general_score, updated_at").eq("user_id", userId).order("updated_at", { ascending: false }).limit(1).maybeSingle(),
      supabase.from("vitals_measurements").select("heart_rate, respiratory_rate, stress_level, spo2, measured_at").eq("user_id", userId).order("measured_at", { ascending: false }).limit(1).maybeSingle()
    ]);
    const payload = {
      latest_scores: scores.data ?? null,
      latest_vitals: vitals.data ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ymexlslqsdflgkcvwjoz";
var mcp_default = defineMcp({
  name: "mayla-mcp",
  title: "Mayla \u2014 Bem-estar Corporativo",
  version: "0.1.0",
  instructions: "Tools for the signed-in Mayla user. Read the user's profile, upcoming appointments, and latest health scores/vitals. All data is descriptive and scoped to the authenticated user \u2014 never diagnostic.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_profile_default, list_my_appointments_default, get_my_health_summary_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
